security:
    providers:
        in_memory:
            memory:
                users:
                    john_doe:
                        password: 'gyRkQzNG8Hp5hCaL'
                        roles: 'ROLE_USER'

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        main:
            anonymous: ~
            http_basic:
                realm: Secured Area

    access_control:
        - { path: ^/api/books, roles: ROLE_USER }
        - { path: ^/api/authors, roles: ROLE_USER }
